site_name: Alive Internet Theory
theme:
  name: material
  palette:
    scheme: slate        # dark mode
    primary: deep purple
    accent: cyan
  features:
    - search.highlight
markdown_extensions:
  - footnotes